export type {
  ConsultationListItem,
  ConsultationDetails,
  ConsultationSlot,
  BookSlotPayload,
  BookSlotRequest,
  BookConsultationWithoutIntervalsRequest,
  BookSlotResponse,
  CreateConsultationPayload,
  CreateConsultationResponse,
  MyConsultationItem,
  UpdateConsultationRequest,
  DeleteConsultationResponse,
  ExportMyConsultationsResponse,
} from './types';